require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'nyc_app' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'react-native-image-base64', :path => '../node_modules/react-native-image-base64'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNFS', :path => '../node_modules/react-native-fs'



  target 'nyc_appTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'nyc_app-tvOS' do
  # Pods for nyc_app-tvOS

  target 'nyc_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
